#!/bin/bash
set -e

myPath=$(realpath "$0")
myDir1=$(dirname "$myPath")
rootDir=$(dirname "$myDir1")

cd $rootDir/pyglossary
ruff --fix .
ruff --select ANN . \
    | grep -v 'Missing type annotation for `self` in method' \
    | grep -v 'Missing type annotation for `\*\*' \
    | grep -v _test.py \
    | grep -v _debug.py \
    | less -R
