#!/bin/bash
set -x
if [ -z "$1" ]; then
	cd $(dirname "$0")/.. || exit
	set .
fi

# ruff check "$@" | grep -E --color=always '\:[0-9]+\:' | less -R
# no 'grep -P' on *BSD / Mac

if [ -z "$NO_COLOR" ]; then
	export CLICOLOR_FORCE=1
fi
ruff check "$@" | less -R
