#!/bin/bash

myPath=$(realpath "$0")
myDir1=$(dirname "$myPath")
rootDir=$(dirname "$myDir1")


if [ -z "$1" ] ; then
	cd $rootDir
	set .
fi

# ruff "$@" | grep -E --color=always '\:[0-9]+\:' | less -R
# no 'grep -P' on *BSD / Mac

if [ -z "$NO_COLOR" ] ; then
	export CLICOLOR_FORCE=1
fi
ruff "$@" | less -R
