#!/usr/bin/env bash
set -e

myDir1=$(dirname "$0")

# to handle rename of a plugin:
rm $myDir1/../doc/p/*.md || true

set -x

python "$myDir1/gen.d/plugin-index.py"
python "$myDir1/gen.d/plugin-doc.py"

python "$myDir1/gen.d/config-doc.py"
python "$myDir1/gen.d/entry-filters-doc.py"
python "$myDir1/gen.d/requirements.py"