#!/usr/bin/env python

import sys
import os
from os.path import abspath, dirname, join

rootDir = dirname(dirname(abspath(__file__)))
sys.path.insert(0, rootDir)

from pyglossary.ui.tools.view_glossary import viewGlossary
from pyglossary.glossary_v2 import Glossary

def main() -> None:
	filename = sys.argv[1]
	format = None
	if len(sys.argv) > 2:
		format = sys.argv[2]

	glos = Glossary(ui=None)
	glos.updateEntryFilters()
	glos.removeHtmlTagsAll()

	filename = os.path.expanduser(filename)
	viewGlossary(filename, format=format, glos=glos)


if __name__ == "__main__":
	main()
