name: Spellcheck
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.34.0
      name: Spellcheck
      with:
        config_path: .github/spellcheck.yml


