name: pypi-publish

on:
  push:
    branches: ["master", "dev"]
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: pypi
      url: https://pypi.org/p/pyglossary
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release
        id: create-release
        run: ./.github/scripts/create-release.sh
      - name: Publish package distributions to PyPI
        if: ( steps.create-release.outputs.skipnext != 'true' )
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
          password: ${{ secrets.PYPI_API_TOKEN }}
