name: "Test - MacOS"

on:
  push:
    branches: ["master", "github-action"]
  pull_request:
  schedule:
    - cron: "33 1 * * 3"

jobs:
  macos:
    name: Mac OS
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: cd and ls
        run: |
          cd ${{ github.workspace }}
          ls -l
      - name: Install Mac-specific dependencies
        run: |
          brew install coreutils pkg-config icu4c
          export PATH="/usr/local/opt/icu4c/bin:/usr/local/opt/icu4c/sbin:$PATH"
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/icu4c/lib/pkgconfig"
          # ensure system clang is used for proper libstdc++
          # https://github.com/ovalhub/pyicu/issues/5#issuecomment-291631507
          unset CC CXX
          python3 -m pip install pyicu
          ln -sf /usr/local/bin/python3 /usr/local/bin/python
      - name: Install dependencies
        run: bash ./scripts/test-deps.sh
      - name: Run tests
        run: bash ./scripts/test.sh
