name: "Validate Plugins"

on:
  push:
    branches: ["master", "dev", "dev2", "github-action"]
  pull_request:
  schedule:
    - cron: "33 1 * * 3"

jobs:
  ubuntu:
    name: "Python 3.13"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: List files
        run: ls -l
      - name: Validate Plugins
        run: python ./scripts/plugin-validate.py
      - name: Try to install requirements.txt
        run: python -m pip install -r requirements.txt
